/*
 * Copyright 2025 Lee Boonstra
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  X,
  FileJson,
  FileSpreadsheet,
  FileCheck2,
  Copy,
  Download,
  Check,
} from 'lucide-react'
import { ActivityEntry, ChainVerificationResult } from './types'
import { cyberAudio } from '../../lib/cyberAudio'
import { useT } from '../../lib/i18n'

interface ActivityExportModalProps {
  isOpen: boolean
  onClose: () => void
  entries: ActivityEntry[]
  verification: ChainVerificationResult | null
  onToast: (msg: string) => void
}

/**
 * Generates comma-separated values (CSV) string from activity entries.
 */
function generateCsv(entries: ActivityEntry[]): string {
  const headers = ['ID', 'Timestamp', 'ISO Date', 'Tool', 'Action', 'Category', 'Status', 'DurationMs', 'SHA256', 'PrevHash', 'Details']
  const rows = entries.map((e) => [
    `"${e.id}"`,
    e.timestamp,
    `"${new Date(e.timestamp).toISOString()}"`,
    `"${(e.toolName || e.toolId || '').replace(/"/g, '""')}"`,
    `"${e.action.replace(/"/g, '""')}"`,
    `"${e.category}"`,
    `"${e.status}"`,
    e.durationMs ?? '',
    `"${e.hash}"`,
    `"${e.prevHash}"`,
    `"${(e.details || '').replace(/"/g, '""')}"`,
  ])

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n')
}

/**
 * Generates a certified cryptographic verification markdown report.
 */
function generateReport(entries: ActivityEntry[], verification: ChainVerificationResult | null): string {
  const now = new Date().toISOString()
  const total = entries.length
  const valid = verification?.valid ?? true
  const totalVerified = verification?.totalVerified ?? total

  return `# NexusHub Workstation — Tamper-Evident Audit Report
Generated: ${now}
Chain Health: ${valid ? 'VALID & UNBROKEN' : 'COMPROMISED DISCONTINUITY'}
Total Audited Events: ${total}
Verified Blocks: ${totalVerified}

## Verification Attestation
This document certifies the cryptographic SHA-256 hash chaining of the local workstation activity ledger. Each audited block contains the SHA-256 hash of its predecessors and canonical event payloads.

- **Chain Status:** ${valid ? 'PASSED (0 Discrepancies)' : 'FAILED (Discontinuity Detected)'}
- **Genesis Block Reference:** ${entries[0]?.hash || 'N/A'}
- **Latest Block Head:** ${entries[entries.length - 1]?.hash || 'N/A'}

## Summary by Category
${['security', 'network', 'system', 'file', 'crypto', 'api']
  .map((cat) => {
    const count = entries.filter((e) => e.category === cat).length
    return `- **${cat.toUpperCase()}**: ${count} operations`
  })
  .join('\n')}

## Detailed Audit Records
| # | Timestamp | Tool | Action | Status | Duration | SHA-256 Hash |
|---|---|---|---|---|---|---|
${entries
  .slice(-100)
  .map(
    (e, idx) =>
      `| ${idx + 1} | ${new Date(e.timestamp).toLocaleTimeString()} | ${e.toolName || e.toolId} | ${e.action} | ${e.status} | ${e.durationMs ?? 0}ms | \`${e.hash.substring(0, 16)}...\` |`
  )
  .join('\n')}

---
*Generated by NexusHub Cryptographic Activity Feed & Audit Journal Engine.*
`
}

/**
 * Triggers a browser/renderer file download with the given data.
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Modal dialog for exporting activity feed in JSON, CSV, or Certified Markdown format.
 */
export const ActivityExportModal: React.FC<ActivityExportModalProps> = ({
  isOpen,
  onClose,
  entries,
  verification,
  onToast,
}) => {
  const { t } = useT()
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null)

  if (!isOpen) return null

  const handleCopy = async (format: 'json' | 'csv' | 'report') => {
    cyberAudio.copySuccess()
    let content = ''
    if (format === 'json') {
      content = JSON.stringify(entries, null, 2)
    } else if (format === 'csv') {
      content = generateCsv(entries)
    } else {
      content = generateReport(entries, verification)
    }

    try {
      await navigator.clipboard.writeText(content)
      setCopiedFormat(format)
      onToast(t('activityFeed.toasts.copied') || 'Copied to clipboard')
      setTimeout(() => setCopiedFormat(null), 2000)
    } catch {}
  }

  const handleDownload = (format: 'json' | 'csv' | 'report') => {
    cyberAudio.copySuccess()
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
    if (format === 'json') {
      const content = JSON.stringify(entries, null, 2)
      downloadFile(content, `nexushub-activity-audit-${timestamp}.json`, 'application/json')
    } else if (format === 'csv') {
      const content = generateCsv(entries)
      downloadFile(content, `nexushub-activity-audit-${timestamp}.csv`, 'text/csv')
    } else {
      const content = generateReport(entries, verification)
      downloadFile(content, `nexushub-audit-verification-report-${timestamp}.md`, 'text/markdown')
    }
    onToast(
      (t('activityFeed.toasts.exported') || 'Audit log exported to {{format}}').replace(
        '{{format}}',
        format.toUpperCase()
      )
    )
  }

  const exportCards = [
    {
      id: 'json' as const,
      title: 'JSON Raw Feed',
      desc:
        t('activityFeed.exportModal.jsonDesc') ||
        'Full raw activity feed with SHA-256 hashes and redacted metadata (JSON format).',
      icon: FileJson,
      color: 'text-nexus-cyan',
      borderColor: 'border-nexus-cyan/30',
      bgColor: 'bg-nexus-cyan/10',
    },
    {
      id: 'csv' as const,
      title: 'Tabular CSV',
      desc:
        t('activityFeed.exportModal.csvDesc') ||
        'Tabular spreadsheet with timestamps, tools, actions, statuses, and hashes (CSV format).',
      icon: FileSpreadsheet,
      color: 'text-emerald-400',
      borderColor: 'border-emerald-500/30',
      bgColor: 'bg-emerald-500/10',
    },
    {
      id: 'report' as const,
      title: 'Certified Audit Report (Markdown)',
      desc:
        t('activityFeed.exportModal.reportDesc') ||
        'Certified Cryptographic Audit Verification Report with SHA-256 merkle proof (Markdown).',
      icon: FileCheck2,
      color: 'text-nexus-accent',
      borderColor: 'border-nexus-accent/30',
      bgColor: 'bg-nexus-accent/10',
    },
  ]

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 overflow-y-auto flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={() => {
            cyberAudio.click()
            onClose()
          }}
          className="fixed inset-0 bg-black/70 backdrop-blur-sm"
        />

        {/* Modal Window */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative w-full max-w-2xl bg-nexus-surface border border-white/10 rounded-2xl shadow-2xl overflow-hidden z-10"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-white/10 bg-nexus-card/80">
            <div>
              <h2 className="text-lg font-bold text-white tracking-tight">
                {t('activityFeed.exportModal.title') || 'Export Audit Journal'}
              </h2>
              <p className="text-xs text-nexus-muted mt-0.5">
                {t('activityFeed.exportModal.description') ||
                  'Download tamper-evident workstation logs for compliance, reporting, or local backup.'}
              </p>
            </div>
            <button
              onClick={() => {
                cyberAudio.click()
                onClose()
              }}
              className="p-1.5 rounded-lg text-nexus-muted hover:text-white hover:bg-white/10 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Cards Body */}
          <div className="p-6 space-y-4">
            {exportCards.map((card) => {
              const Icon = card.icon
              const isCopied = copiedFormat === card.id

              return (
                <div
                  key={card.id}
                  className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl border border-white/5 bg-nexus-card/60 hover:bg-nexus-card transition-all"
                >
                  <div className="flex items-start gap-3.5 flex-1 min-w-0">
                    <div
                      className={`w-10 h-10 rounded-xl ${card.bgColor} border ${card.borderColor} flex items-center justify-center flex-shrink-0 ${card.color}`}
                    >
                      <Icon className="w-5 h-5" />
                    </div>
                    <div>
                      <h3 className="text-sm font-semibold text-white">{card.title}</h3>
                      <p className="text-xs text-nexus-muted mt-0.5 max-w-md">{card.desc}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 self-end sm:self-center flex-shrink-0">
                    <button
                      onClick={() => handleCopy(card.id)}
                      className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium bg-nexus-surface border border-white/10 text-nexus-text hover:text-white hover:border-white/20 transition-all"
                    >
                      {isCopied ? (
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                      <span>{isCopied ? 'Copied' : 'Copy'}</span>
                    </button>

                    <button
                      onClick={() => handleDownload(card.id)}
                      className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-nexus-cyan/20 border border-nexus-cyan/40 text-nexus-cyan hover:bg-nexus-cyan/30 transition-all shadow-sm"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>{t('activityFeed.exportModal.download') || 'Download'}</span>
                    </button>
                  </div>
                </div>
              )
            })}
          </div>

          {/* Footer */}
          <div className="p-4 border-t border-white/10 bg-nexus-card/60 flex items-center justify-end">
            <button
              onClick={() => {
                cyberAudio.click()
                onClose()
              }}
              className="px-4 py-2 rounded-lg text-xs font-medium bg-white/5 border border-white/10 text-nexus-text hover:bg-white/10 transition-all"
            >
              {t('activityFeed.exportModal.cancel') || 'Cancel'}
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}

export default ActivityExportModal
