/*
 * Copyright 2025 Lee Boonstra
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ActivityEntry, ChainVerificationResult } from './types'

/**
 * Generates comma-separated values (CSV) string from activity entries with RFC-4180 escaping.
 */
export function generateCsv(entries: ActivityEntry[]): string {
  const headers = [
    'ID',
    'Timestamp',
    'ISO Date',
    'Tool',
    'Action',
    'Category',
    'Status',
    'DurationMs',
    'SHA256',
    'PrevHash',
    'Details',
  ]
  const rows = entries.map((e) => [
    `"${e.id}"`,
    e.timestamp,
    `"${new Date(e.timestamp).toISOString()}"`,
    `"${(e.toolName || e.toolId || '').replace(/"/g, '""')}"`,
    `"${e.action.replace(/"/g, '""')}"`,
    `"${e.category}"`,
    `"${e.status}"`,
    e.durationMs ?? '',
    `"${e.hash}"`,
    `"${e.prevHash}"`,
    `"${(e.details || '').replace(/"/g, '""')}"`,
  ])

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n')
}

/**
 * Generates a certified cryptographic verification markdown report.
 */
export function generateReport(
  entries: ActivityEntry[],
  verification: ChainVerificationResult | null
): string {
  const now = new Date().toISOString()
  const total = entries.length
  const valid = verification?.valid ?? true
  const totalVerified = verification?.totalVerified ?? total

  return `# NexusHub Workstation — Tamper-Evident Audit Report
Generated: ${now}
Chain Health: ${valid ? 'VALID & UNBROKEN' : 'COMPROMISED DISCONTINUITY'}
Total Audited Events: ${total}
Verified Blocks: ${totalVerified}

## Verification Attestation
This document certifies the cryptographic SHA-256 hash chaining of the local workstation activity ledger. Each audited block contains the SHA-256 hash of its predecessors and canonical event payloads.

- **Chain Status:** ${valid ? 'PASSED (0 Discrepancies)' : 'FAILED (Discontinuity Detected)'}
- **Genesis Block Reference:** ${entries[0]?.hash || 'N/A'}
- **Latest Block Head:** ${entries[entries.length - 1]?.hash || 'N/A'}

## Summary by Category
${['security', 'network', 'system', 'file', 'crypto', 'api']
  .map((cat) => {
    const count = entries.filter((e) => e.category === cat).length
    return `- **${cat.toUpperCase()}**: ${count} operations`
  })
  .join('\n')}

## Detailed Audit Records
| # | Timestamp | Tool | Action | Status | Duration | SHA-256 Hash |
|---|---|---|---|---|---|---|
${entries
  .slice(-100)
  .map(
    (e, idx) =>
      `| ${idx + 1} | ${new Date(e.timestamp).toLocaleTimeString()} | ${e.toolName || e.toolId} | ${e.action} | ${e.status} | ${e.durationMs ?? 0}ms | \`${e.hash.substring(0, 16)}...\` |`
  )
  .join('\n')}

---
*Generated by NexusHub Cryptographic Activity Feed & Audit Journal Engine.*
`
}

/**
 * Triggers a browser/renderer file download with the given data.
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Quick direct CSV download with timestamped filename.
 */
export function quickExportCsv(entries: ActivityEntry[]): void {
  const csv = generateCsv(entries)
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  downloadFile(csv, `nexushub-activity-audit-${timestamp}.csv`, 'text/csv;charset=utf-8;')
}

/**
 * Quick direct JSON download with timestamped filename.
 */
export function quickExportJson(entries: ActivityEntry[]): void {
  const json = JSON.stringify(entries, null, 2)
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  downloadFile(json, `nexushub-activity-audit-${timestamp}.json`, 'application/json;charset=utf-8;')
}
